CREATE TABLE voting_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL UNIQUE REFERENCES agendas (id),
    opened_at TIMESTAMP NOT NULL,
    duration_minutes INTEGER NOT NULL
);
