CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL REFERENCES agendas (id),
    member_id BIGINT NOT NULL,
    vote_answer VARCHAR(10) NOT NULL,
    registered_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_votes_agenda_member UNIQUE (agenda_id, member_id)
);
